"""Country-name helpers for Comtrade numeric market codes."""

from __future__ import annotations

from typing import Any

# Comtrade mostly uses UN M49 numeric codes, but some responses omit leading
# zeroes and a few common reporters use Comtrade-specific numeric variants.
COUNTRY_NAMES_BY_CODE = {
    "004": "Afghanistan",
    "008": "Albania",
    "012": "Algeria",
    "016": "American Samoa",
    "020": "Andorra",
    "024": "Angola",
    "028": "Antigua and Barbuda",
    "031": "Azerbaijan",
    "032": "Argentina",
    "036": "Australia",
    "040": "Austria",
    "044": "Bahamas",
    "051": "Armenia",
    "050": "Bangladesh",
    "052": "Barbados",
    "048": "Bahrain",
    "056": "Belgium",
    "064": "Bhutan",
    "060": "Bermuda",
    "068": "Bolivia",
    "070": "Bosnia and Herzegovina",
    "072": "Botswana",
    "074": "Bouvet Island",
    "076": "Brazil",
    "084": "Belize",
    "086": "British Indian Ocean Territory",
    "090": "Solomon Islands",
    "092": "British Virgin Islands",
    "096": "Brunei",
    "100": "Bulgaria",
    "108": "Burundi",
    "104": "Myanmar",
    "112": "Belarus",
    "116": "Cambodia",
    "120": "Cameroon",
    "124": "Canada",
    "132": "Cabo Verde",
    "136": "Cayman Islands",
    "140": "Central African Republic",
    "144": "Sri Lanka",
    "148": "Chad",
    "152": "Chile",
    "156": "China",
    "162": "Christmas Island",
    "170": "Colombia",
    "174": "Comoros",
    "178": "Congo",
    "180": "Democratic Republic of the Congo",
    "184": "Cook Islands",
    "188": "Costa Rica",
    "192": "Cuba",
    "191": "Croatia",
    "196": "Cyprus",
    "203": "Czechia",
    "204": "Benin",
    "208": "Denmark",
    "212": "Dominica",
    "214": "Dominican Republic",
    "218": "Ecuador",
    "222": "El Salvador",
    "226": "Equatorial Guinea",
    "232": "Eritrea",
    "231": "Ethiopia",
    "233": "Estonia",
    "234": "Faroe Islands",
    "238": "Falkland Islands",
    "242": "Fiji",
    "246": "Finland",
    "251": "France",
    "258": "French Polynesia",
    "262": "Djibouti",
    "266": "Gabon",
    "268": "Georgia",
    "270": "Gambia",
    "275": "Palestine",
    "276": "Germany",
    "288": "Ghana",
    "292": "Gibraltar",
    "300": "Greece",
    "308": "Grenada",
    "316": "Guam",
    "320": "Guatemala",
    "324": "Guinea",
    "328": "Guyana",
    "332": "Haiti",
    "340": "Honduras",
    "344": "Hong Kong",
    "348": "Hungary",
    "352": "Iceland",
    "356": "India",
    "360": "Indonesia",
    "364": "Iran",
    "368": "Iraq",
    "372": "Ireland",
    "376": "Israel",
    "380": "Italy",
    "384": "Cote d'Ivoire",
    "388": "Jamaica",
    "392": "Japan",
    "398": "Kazakhstan",
    "400": "Jordan",
    "404": "Kenya",
    "410": "South Korea",
    "414": "Kuwait",
    "417": "Kyrgyzstan",
    "418": "Laos",
    "422": "Lebanon",
    "426": "Lesotho",
    "428": "Latvia",
    "430": "Liberia",
    "434": "Libya",
    "440": "Lithuania",
    "442": "Luxembourg",
    "446": "Macao",
    "450": "Madagascar",
    "454": "Malawi",
    "458": "Malaysia",
    "462": "Maldives",
    "466": "Mali",
    "470": "Malta",
    "478": "Mauritania",
    "480": "Mauritius",
    "484": "Mexico",
    "490": "Other Asia, n.e.s.",
    "498": "Moldova",
    "499": "Montenegro",
    "496": "Mongolia",
    "504": "Morocco",
    "508": "Mozambique",
    "512": "Oman",
    "516": "Namibia",
    "520": "Nauru",
    "524": "Nepal",
    "528": "Netherlands",
    "531": "Curacao",
    "533": "Aruba",
    "534": "Sint Maarten",
    "535": "Bonaire, Sint Eustatius and Saba",
    "540": "New Caledonia",
    "548": "Vanuatu",
    "554": "New Zealand",
    "558": "Nicaragua",
    "562": "Niger",
    "566": "Nigeria",
    "568": "Other Europe, n.e.s.",
    "570": "Niue",
    "574": "Norfolk Island",
    "577": "Other Oceania, n.e.s.",
    "579": "Norway",
    "581": "United States Minor Outlying Islands",
    "583": "Micronesia",
    "584": "Marshall Islands",
    "586": "Pakistan",
    "591": "Panama",
    "598": "Papua New Guinea",
    "600": "Paraguay",
    "604": "Peru",
    "608": "Philippines",
    "616": "Poland",
    "620": "Portugal",
    "624": "Guinea-Bissau",
    "626": "Timor-Leste",
    "634": "Qatar",
    "642": "Romania",
    "643": "Russia",
    "646": "Rwanda",
    "652": "Saint Barthelemy",
    "659": "Saint Kitts and Nevis",
    "660": "Anguilla",
    "662": "Saint Lucia",
    "666": "Saint Pierre and Miquelon",
    "670": "Saint Vincent and the Grenadines",
    "678": "Sao Tome and Principe",
    "682": "Saudi Arabia",
    "686": "Senegal",
    "688": "Serbia",
    "690": "Seychelles",
    "694": "Sierra Leone",
    "699": "India",
    "702": "Singapore",
    "703": "Slovakia",
    "704": "Vietnam",
    "705": "Slovenia",
    "706": "Somalia",
    "710": "South Africa",
    "716": "Zimbabwe",
    "724": "Spain",
    "728": "South Sudan",
    "729": "Sudan",
    "740": "Suriname",
    "748": "Eswatini",
    "760": "Syria",
    "762": "Tajikistan",
    "764": "Thailand",
    "768": "Togo",
    "772": "Tokelau",
    "776": "Tonga",
    "780": "Trinidad and Tobago",
    "796": "Turks and Caicos Islands",
    "798": "Tuvalu",
    "752": "Sweden",
    "757": "Switzerland",
    "788": "Tunisia",
    "795": "Turkmenistan",
    "784": "United Arab Emirates",
    "792": "Turkey",
    "804": "Ukraine",
    "807": "North Macedonia",
    "800": "Uganda",
    "818": "Egypt",
    "826": "United Kingdom",
    "834": "Tanzania",
    "842": "United States",
    "854": "Burkina Faso",
    "858": "Uruguay",
    "860": "Uzbekistan",
    "862": "Venezuela",
    "882": "Samoa",
    "887": "Yemen",
    "894": "Zambia",
    "899": "Areas, n.e.s.",
}


def resolve_country_name(country_code: Any, candidate: Any = None) -> str | None:
    """
    Return a displayable country name for a Comtrade market code.

    Falls back to "Unknown ({code})" rather than None for any code not in
    COUNTRY_NAMES_BY_CODE and not resolved from Comtrade's own description --
    callers (e.g. competitor_flows.supplier_name) rely on a non-null result,
    and the static table can't guarantee full UN M49 coverage.
    """
    cleaned = _clean_candidate(candidate)
    if cleaned:
        return cleaned

    code = str(country_code).strip() if country_code is not None else ""
    if not code:
        return None

    variants = [code]
    if code.isdigit():
        variants.extend([code.zfill(3), str(int(code))])

    for variant in variants:
        name = COUNTRY_NAMES_BY_CODE.get(variant)
        if name:
            return name
    return f"Unknown ({code})"


def _clean_candidate(value: Any) -> str | None:
    if value is None:
        return None

    text = str(value).strip()
    if not text or text.lower() in {"none", "nan", "null", "<na>"}:
        return None
    if text.isdigit():
        return None
    return text
